name:                calculator
version:             0.1.0.0
github:              SaxJ/hcalc
license:             BSD3
author:              Saxon Jensen
maintainer:          saxon.jensen@gmail.com
copyright:           2020 Saxon Jensen

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/SaxJ/hcalc#readme>

dependencies:
- base >= 4.11 && < 10

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  calculator-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - calculator
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  calculator-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - calculator
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
